# Generated by Django 5.1.2 on 2024-11-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='notas',
            new_name='nota',
        ),
    ]
